version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stat
      - SPRING_DATASOURCE_USERNAME=greenwolf
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      - POSTGRES_DB=ewm_stat
      - POSTGRES_USER=greenwolf
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service
      - SPRING_DATASOURCE_USERNAME=greenwolf
      - SPRING_DATASOURCE_PASSWORD=password
      - STAT_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm_service
      - POSTGRES_USER=greenwolf
      - POSTGRES_PASSWORD=password
